name: Flutter MultiPlatform Build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
      - name: Flutter Android Build
        run: |
          flutter pub get
          flutter analyze
          flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          architecture: x64
      - name: Flutter IOS Build
        run: |
          flutter pub get
          flutter analyze
          flutter build ipa --release --no-codesign
      - uses: actions/upload-artifact@v1
        with:
          path: /Users/runner/work/GuardianDock/GuardianDock/build/ios/archive/Runner.xcarchive
