name: Flutter MultiPlatform Build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Flutter Install
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          architecture: x64
          cache: true
      - name: Flutter Android Build
        run: |
          flutter pub get
          flutter analyze
          flutter build apk --dart-define=BNG_API_KEY=${{ secrets.SECRET_API_KEY }}
      - uses: actions/upload-artifact@v1
        with:
          name: release-android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Flutter Install
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          architecture: x64
          cache: true
      - name: Flutter IOS Build
        run: |
          flutter pub get
          flutter analyze
          flutter build ipa --release --no-codesign --dart-define=BNG_API_KEY=${{ secrets.SECRET_API_KEY }}
      - uses: actions/upload-artifact@v1
        with:
          name: Runner.xcarchive
          path: /Users/runner/work/GuardianDock/GuardianDock/build/ios/archive/Runner.xcarchive
